### ISSUE TITLE
Support for addition options when issueing a cert

### ISSUE THREAD

**Issue by hexedpackets** [issacg/vault-pki-client#2]
I've been trying out vault-pki-client and found that I need some additional options passed through when issueing a certificate. In particular, I have a server that clients reach on two different DNS addresses so I need to set alt_names for the cert.

Is this a planned addition? Would you accept a PR for it if I added it?

**Comment by issacg** [comment]
I wanted it myself, but didn't have enough cycles to test it + rebuild the binaries.

A PR would be great, but I'm not sure if I'd have time to rebuild the binaries
